# Generated by Django 4.0.5 on 2022-06-30 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.IntegerField(default=0)),
                ('poids', models.IntegerField(default=0)),
                ('today_steps', models.IntegerField(default=0)),
                ('total_steps', models.IntegerField(default=0)),
                ('categ', models.CharField(max_length=50)),
                ('chat_path', models.CharField(default='', max_length=200)),
                ('data_path', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
