# Generated by Django 4.0.5 on 2022-06-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_user_access_token_r_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='school',
            field=models.CharField(default='um6p', max_length=50),
        ),
    ]
