# Generated by Django 4.0.5 on 2022-07-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_data_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='chat_path',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='data_path',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
