# Generated by Django 4.0.5 on 2022-07-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_data_chat_path_alter_data_data_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='compets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.TextField()),
                ('date', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('showing', models.IntegerField(default=0)),
            ],
        ),
    ]
